### ISSUE TITLE
Secondary Quote Currency

### ISSUE THREAD

**Issue by camray** [altangent/cryptolist#53]
Add a drop down box on the right side of the current quote picker for a secondary quote picker. The secondary quote will dictate a 'secondary price' that will be shown in the sidebar. If the market of `Selected Currency -> Primary Quote Currency` does not exist, the primary quote currency will be replaced with the secondary quote currency for the main chart data.

## Decisions that need to be made
- How will we clearly indicate which currency is being used, primary or secondary?
- Where should secondary quote currency be stored? The primary is stored in the URL. Maybe for secondary we should store it in local storage. In that case we should also store the primary in local storage and use it in the URL if the user did not request a primary currency in the URL.

## TODO
- [ ] Display second drop down box (perhaps smaller in size) in the navbar for secondary quote currency with the same options as primary
- [ ] Initial drop down selection is pulled from local storage
- [ ] When changed `secondaryQuote` local storage value is updated to selection value. Additionally state is updated to re-render the app
- [ ] Do not re-render the main chart if the secondary quote was changed but we're already using the primary quote
